HOST: https://knowledge-gateway.org/global/__api/v2

--- Ecs API v2 ---

-- Library --

List all library tags. It returns a list of tags whether the library is in folder or tag mode.
GET /tags
> Accept: application/json
< 200
< Content-Type: application/json
